server.port=8080

spring.application.name=reading-assignment

spring.datasource.url=jdbc:h2:mem:reading_assignment
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
# avoid storing passwords in plain text, use a password manager like 1Password or LastPass or secrets manager instead
spring.datasource.password=<password>

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.cors.allowed-origin=http://localhost:4200
