server.port=8080

spring.application.name=reading-assignment

spring.datasource.url=jdbc:h2:mem:reading_assignment
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
# avoid storing passwords in plain text, use a password manager like 1Password or LastPass or secrets manager instead
spring.datasource.password=<password>

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Allow remote access to the H2 console.
# Render requires this to be able to open the console
# SECURITY WARNING: Enabling webAllowOthers means anyone with network access to your host IP and port can hit your database console.
# Never enable this setting in a production environment without putting the console behind a secure reverse proxy, a VPN, or configuring strict firewall rules.
spring.h2.console.settings.web-allow-others=true


app.cors.allowed-local-origin=http://localhost:4200
app.cors.allowed-prod-origin=https://reading-assignment-ui.vercel.app
